development:
  adapter: postgresql
  encoding: unicode
  database: mobile_form_generator_api_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: mobile_form_generator_api_test
  pool: 5
  username: postgres
  password: postgres